resolver: nightly-2020-02-23
packages:
- .

extra-deps:
  - git: https://github.com/ndmitchell/shake.git
    commit: 79a098c55f62de9efd851546435945b7f7f9b9df
  - git: https://github.com/spall/rattle.git
    commit: f1f10504ef175dd005c8affdddfc1fb615c040f2