resolver: nightly-2020-02-23
packages:
- .

extra-deps:
  - git: https://github.com/ndmitchell/shake.git
    commit: a322c0c1b793dbe4c822276708aee40ef5a73bd0
  - git: https://github.com/ndmitchell/rattle.git
    commit: 5a4160ef04e5cf89f6ceb91c59a38177fc562bb4