
module C.Config(cc, cppflags, cflags, zLibDep, lz4Dep, zLibLib, lz4Lib, nCursesLib
               ,zLibInc, lz4Inc, ar, arFlags, ldflags) where

-- generated by config so...... figure that out
-- for now these values were just copied from a generated one

cc = "gcc"
cppflags = []
cflags = []
ld = "ld"
ldflags = [] 
ar = "ar"
arFlags = "rc"
ranlib = "ranlib"
windres = "windres"
cursesLib = "-lcurses"
nCursesLib ="-lncurses"
zLibInc = "-I../zlib"
lz4Inc = "-I../lz4/lib"
zLibDep = "../zlib/libz.a"
lz4Dep = "../lz4/lib/liblz4.a"
zLibLib = "../zlib/libz.a"
lz4Lib = "../lz4/lib/liblz4.a"
zLibHeaderDep = ["../zlib/zconf.h", "../zlib/zlib.h"]
lz4HeaderDep = ["../lz4/lib/lz4.h", "../lz4/lib/lz4frame.h"]
-- kernel = kernelLib
-- kernelLinkDeps = kernelLibLinkDeps
-- kernelLinkLibs = kernelLibLinkLibs
